<footer class="footer row mt-5">
	<div class="container mt-5">
		<div class="row ">
			<div class="col-md-12 mt-5 text-center">
				<h1 class="concert-one-regular">WebbyDev Farms, Inc.</h1>
				<div class="col-md-12 mt-5 text-center">
				<ul class="footer-links-list">
					<li class="footer-link"><a href="/scsuproject/site/">Home</a></li>
					<li class="footer-link"><a href="/scsuproject/site/view/inventory.php">Inventory</a></li>
					<li class="footer-link"><a href="/scsuproject/site/view/about.php">About Us</a></li>
					<li class="footer-link"><a href="/scsuproject/site/view/contact.php">Contact</a></li>
				</ul>
				<ul class="footer-links-list">
					<li class="footer-link"><a href=""><i class="fa fa-facebook"><img src="/scsuproject/site/img/social-media/facebook_1.png" alt="Facebook" width="50" height="50"></i></a></li>
					<li class="footer-link"><a href=""><i class="fa fa-facebook"><img src="/scsuproject/site/img/social-media/twitter_1.png" alt="Twitter" width="50" height="50"></i></a></li>
					<li class="footer-link"><a href=""><i class="fa fa-facebook"><img src="/scsuproject/site/img/social-media/pinterest_1.png" alt="Pinterest" width="50" height="50"></i></a></li>
					<li class="footer-link"><a href=""><i class="fa fa-facebook"><img src="/scsuproject/site/img/social-media/google-plus_1.png" alt="Google Plus" width="50" height="50"></i></a></li>
					<li class="footer-link"><a href=""><i class="fa fa-facebook"><img src="/scsuproject/site/img/social-media/instagram_1.png" alt="Instagram" width="50" height="50"></i></a></li>
				<ul>
			</div>
			<div class="col-md-12 text-center mt-5">
				<p id="footer-company-name">Brenfernanchek Projects &copy; 2024-<script type="text/javascript">document.write(new Date().getFullYear());</script> - All Rights Reserved.</p>
			</div>
		</div>
	</div>
</footer>